name: Release Drafter

on:
  push:
    branches:
      - main

# Default permissions granted to the GITHUB_TOKEN
permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write       # to create a github release
      pull-requests: read   # to read pr details (only update to write if adding labels to the PR)
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
